package edu.baylor.csi3471.netime_planner.gui.windows;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.baylor.csi3471.netime_planner.gui.command.OpenUserScheduleCommand;
import edu.baylor.csi3471.netime_planner.gui.screens.ProfileScreen;
import edu.baylor.csi3471.netime_planner.models.domain_objects.User;

import javax.swing.*;
import java.awt.*;

public class MainWindow extends JFrame {
    private final User user;
    private JTabbedPane tabbedPane1;
    private JPanel profilePanel;
    private JPanel mainPanel;

    public MainWindow(User user) {
        this.user = user;
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setTitle("NETime Planner");

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        pack();
    }

    public void addTab(String title, JPanel tab) {
        tabbedPane1.addTab(title, tab);
        tabbedPane1.setSelectedIndex(tabbedPane1.getTabCount() - 1);
    }

    private void createUIComponents() {
        var profileScreen = new ProfileScreen(user.getName());
        profilePanel = profileScreen.getPanel();
        profileScreen.setViewScheduleButtonCommand(new OpenUserScheduleCommand(this, user));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1 = new JTabbedPane();
        mainPanel.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        tabbedPane1.addTab("Profile", profilePanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }


}
