package edu.baylor.csi3471.netime_planner.gui.windows;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.baylor.csi3471.netime_planner.gui.ActivityListCellRenderer;
import edu.baylor.csi3471.netime_planner.gui.form.WorktimeForm;
import edu.baylor.csi3471.netime_planner.models.domain_objects.Activity;
import edu.baylor.csi3471.netime_planner.models.domain_objects.Schedule;
import edu.baylor.csi3471.netime_planner.services.ScheduleService;
import edu.baylor.csi3471.netime_planner.services.ServiceManager;

import javax.swing.*;
import java.awt.*;

public class WorktimesWindow extends JDialog {
    private final Schedule schedule;
    private JComboBox<Activity> box;
    private JButton addButton;
    private JButton editButton;
    private JButton deleteButton;
    private JPanel mainPanel;

    public WorktimesWindow(Schedule s) {
        this.schedule = s;
        $$$setupUI$$$();
        box.setRenderer(new ActivityListCellRenderer());
        for (var wt : schedule.getWorkTimes()) {
            box.addItem(wt);
        }
        setContentPane(mainPanel);
        setTitle("Work Times");

        addButton.addActionListener(e -> {
            var form = new WorktimeForm();
            form.setSubmissionListener(ev -> {
                var newWt = form.getCreatedValue();
                ServiceManager.getInstance().getService(ScheduleService.class).addWorktime(schedule, newWt);
                box.addItem(newWt);
                form.setVisible(false);
            });
            form.setVisible(true);
        });

        deleteButton.addActionListener(e -> {
            if (box.getSelectedIndex() == -1)
                return;
            ServiceManager.getInstance().getService(ScheduleService.class).removeWorktime(schedule, (Activity) box.getSelectedItem());
            box.removeItemAt(box.getSelectedIndex());
        });

        pack();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 3, new Insets(5, 5, 5, 5), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, 1, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(194, 240), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Current work times");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        box = new JComboBox();
        panel1.add(box, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(200, -1), null, null, 0, false));
        addButton = new JButton();
        addButton.setText("Add...");
        mainPanel.add(addButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        editButton = new JButton();
        editButton.setText("Edit...");
        mainPanel.add(editButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteButton = new JButton();
        deleteButton.setText("Delete");
        mainPanel.add(deleteButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
